### ISSUE TITLE
Errors with Building a UK Vagrant, Virtualbox VM 

### ISSUE THREAD

**Issue by aidandunsdon** [openfoodfoundation/ofn_deployment#12]
Transferring this issue from OFN UK Dev group and attaching link to errors in command line output at https://gist.github.com/aidandunsdon/c8ba12b4a9e0c088d14c

I am assisting Stroudco in the UK in transitioning to OFN. One of my first jobs has been to build a local dev environment in vagrant / virtual box using the Ansible playbooks from https://github.com/openfoodfoundation/ofn_deployment.
 My first issue was that I am using a windows 7 machine which does not directly support Ansible. Fortunately I came across a working solution which uses a shell file to bootstrap the vagrant VM by installing Ansible on the guest and then letting ansible do the provisioning in local connection mode from the VM.
 I had to install zzet.rbenv and mortik.nginx-rails from ansible-galaxy and copied the the UK seed files manually to the input files directory. The build seemed to get a long way through but fails after throwing an error message "Failed to lock apt for exclusive operation"  (First appears at line 181 in attached command output file) . I googled this and found a recommendation to add a -s parameter to 

sudo ansible-playbook -s /vagrant/install.yml --connection=local

which makes all plays sudo but to no avail. I would be grateful if you are able to shed any light on this as I feel that I am nearly there with building a dev server.

Many Thanks

Aidan

Command output at https://gist.github.com/aidandunsdon/c8ba12b4a9e0c088d14c

**Comment by pmackay** [comment]
@aidandunsdon do you still want to keep this open?

**Comment by aidandunsdon** [comment]
@pmackay yes I think I would like to get to the bottom of this having invested so much time

**Comment by mkllnk** [comment]
@aidandunsdon Are you still working on this?

**Comment by aidandunsdon** [comment]
@mkllnk Not recently - would be good to get a working Vagrant VM at some point though - I am tied up at the moment though. Do you want me close this for now?

**Comment by mkllnk** [comment]
> would be good to get a working Vagrant VM at some point though

We did Vagrant test runs from time to time and it worked. The project got changed a lot in the last couple of months as well. So maybe close it for now and open a new, more specific issue if you encounter a problem again.
