### ISSUE TITLE
Travis-run Ansible build deploying to Digital Ocean fails with "something went wrong" page

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/ofn_deployment#23]
It returns this output:

```
failed: [localhost] => {"connection": "keep-alive", "content": "<!DOCTYPE html>\n<html>\n<head>\n  <title>We're sorry, but something went wrong (500)</title>\n  <style type=\"text/css\">\n    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }\n    div.dialog {\n      width: 25em;\n      padding: 0 4em;\n      margin: 2em auto 0 auto;\n    }\n    a.go_home { \n      font-size: 100%; \n      color: black; \n      line-height: 1.5em; \n      text-decoration: none;\n      border-bottom: 1px dotted black;\n      padding: 0 0.2rem;\n    }\n    a.go_home:hover, a.go_home:focus, a.go_home:active{\n      background: #8f301d;\n      color: white;\n      border-bottom: none;\n    }\n  </style>\n</head>\n\n<body>\n  <!-- This file lives in public/500.html -->\n  <div class=\"dialog\">\n    <a href=\"/\" ><img src=\"/500.jpg\" /></a>\n    <p>We're sorry, but something went wrong. \n      <br>Try refreshing the page, or\n      <br><h3><a class=\"go_home\" href=\"/\" >Return home</a></h3>\n      <br>Want to let us know what went wrong? Email us at: \n      <h3>\n        <!-- Can we do .reverse ??\n        <a class=\"go_home\" href=\"mailto:hello@openfoodnetwork.org\" target=\"_blank\"></a>\n        -->\n        hello [at] openfoodnetwork.org\n      </h3>\n    </p>\n  </div>\n</body>\n</html>\n", "content_length": "1219", "content_type": "text/html", "date": "Mon, 12 Jan 2015 17:44:16 GMT", "etag": "\"54b4042b-4c3\"", "failed": true, "redirected": false, "server": "nginx/1.6.2 (Ubuntu)", "status": 504}
msg: Status code was not [200]
```

**Comment by rafaqz** [comment]
Looks like the codebase is somehow broken after the push. Have you checked the logs to see what's failing?

**Comment by pmackay** [comment]
Sorry, I should have been clearer, this is only happening in a completely
automated build via Travis. If I then load the site manually it works, so
I'm not sure why pulling the homepage via Travis is not returning the
homepage. Its the last thing preventing a full full successful test via
Travis.

I probably shouldnt have raised this here, as its only an issue on this
branch https://github.com/folklabs/ofn_deployment/tree/travis-digitalocean
currently. Not merged yet.

**Comment by rafaqz** [comment]
Ok no worries, good to see that you have the travis build mostly working
anyway.

Not sure how travis would be making a different request to a normal page
load, might be good to test if nginx/unicorn is actually up at the end of
the ansible run? nginx then unicorn restarts should be the last things that
happen...

**Comment by pmackay** [comment]
I think the services are started cos if I visit the droplet IP via a
browser it works....

**Comment by rafaqz** [comment]
weird. tried adding some kind of delay?

**Comment by pmackay** [comment]
Fixed in https://github.com/folklabs/ofn_deployment/commit/bfd209bd1501a5f165a644c71d2ac503faeafa6c.
