### ISSUE TITLE
Admin account creation isnt working

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/ofn_deployment#24]
Currently it uses a `seed.sh` template to create a shell script that calls `db:seed` to generate an admin account, but the command that seems to be used for creating admin accounts is:

`bundle exec rake spree_auth:admin:create`

At least the current `db:seed` operation is not doing that.

**Comment by rafaqz** [comment]
Spree seeding automatically makes an admin account, and installing manually
you need to input email and password or just hit enter twice for defaults.
But that of course halts any automation.

The little bash script
<https://github.com/openfoodfoundation/ofn_deployment/blob/master/roles/app/templates/seed.sh.j2>
is used to get around this, it passes the username and password with an EOF
block, which was harder to do in straight ansible. It definately works or
was working recently.

**Comment by pmackay** [comment]
I'm wondering if the seeds.rb file has changed and isnt creating an admin
user now? I dont think its the bash script thats the problem. Will do more
digging...

**Comment by pmackay** [comment]
Or do you mean that `db:seed` via Spree would automatically create an admin account anyway? Cos I tested it locally and it didnt seem to on recent codebase.

**Comment by pmackay** [comment]
I think this *isnt* an issue, its probably something about the staging server thats got mixed up.

**Comment by kirstenalarsen** [comment]
@pmackay hi paul, can you confirm that this is ok now, what you did to get it sorted and whether the default is then spree@example.com? Just that I know someone else is having trouble with this

**Comment by pmackay** [comment]
I did more testing and learnt a bit more about it. I'm assuming that the current script works but am not sure quite what state the staging installation got into. I'll try to run another install test for my own benefit. It would take the `admin_email` and `admin_pass` from the `vars.yml` file. 

`db:seed` doesnt rerun adding an admin account if its already been done, unless you reset the database. 

What problems are you hearing about?
