### ISSUE TITLE
Support deploying to different servers from one project

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/ofn_deployment#25]
Currently to use ofn_deployment you have to put SSL certs in /files and define a vars.yml file with settings for just 1 domain. It would be great if one copy of the project could be used to manage staging and production with different inventory files.

* SSL certs could be put into subdirectores matching the `rails_env` var.
* Maybe vars.yml could be named according to the env too, or have some variables in a hash per env.

**Comment by rafaqz** [comment]
that sounds good. then we can push to specific server from the command line specifing the rails_env?

**Comment by pmackay** [comment]
> push to specific server from the command line specifing the rails_env?

@rafaqz how do you mean? Can you give an example?

**Comment by rafaqz** [comment]
I was imaging you could break servers into groups called production/staging
etc in the inventory, so you could push to multiple staging servers at once
that were all in that group, if that sitation ever arose.

**Comment by pmackay** [comment]
Have updated the docs here https://github.com/openfoodfoundation/ofn_deployment/wiki/Setup with a new method.
