### ISSUE TITLE
Bugsnag is broken

### ISSUE THREAD

**Issue by rafaqz** [openfoodfoundation/ofn_deployment#28]
For some reason bugsnag does not with our current setup, the config isn't being pulled in.

**Comment by pmackay** [comment]
@RohanM @oeoeaio @kirstenalarsen can you tell me about the setup of Bugsnag? It looks like their free plan is limited - does OFN pay for an account? How could we get it setup for the UK?

**Comment by mkllnk** [comment]
I think this has been fixed.

@pmackay We added your servers to our account which we pay for. Bugsnag writes about the [free plan](https://bugsnag.com/blog/announcing-paid-plans):

> Free Plan
> 
> Includes 2,000 exceptions/month, one user and unlimited projects. Premium features such as chatroom notification, ticket creation, error resolving and deploy tracking are not included.
