### ISSUE TITLE
Support setup of delayed jobs

### ISSUE THREAD

**Issue by pmackay** [openfoodfoundation/ofn_deployment#30]
Notes from Rohan:

> monit daemon

> check process openfoodnetwork_dj_worker_0
with pidfile /home/openfoodweb/apps/openfoodweb/current/tmp/pids/delayed_job.0.pid
start program = "/bin/bash -c 'RAILS_ENV=staging /home/openfoodweb/apps/openfoodweb/current/script/delayed_job.sh -i 0 start'"
as uid openfoodweb and gid openfoodweb
with timeout 120 seconds
stop program = "/bin/bash -c 'RAILS_ENV=staging /home/openfoodweb/apps/openfoodweb/current/script/delayed_job.sh -i 0 stop'"
as uid openfoodweb and gid openfoodweb
with timeout 120 seconds
if mem is greater than 250.0 MB for 3 cycles then restart
group dj_workers

> script/delayed_job.sh

> When you deploy, you need to restart delayed job also
RAILS_ENV=staging ./script/delayed_job -i 0 stop

**Comment by pmackay** [comment]
@RohanM I think this is needed to resolve our email issue! And its been on my plate for ages, just not got round to it. Could you please help with a bit more info:

Where should this monit file go? The default `~/.monitrc`?

The `script/delayed_job.sh` file has coded paths like `$HOME/apps/openfoodweb/current/script/delayed_job`. What would be the best way to make that configurable? (same question applies to other CI scripts)

**Comment by RohanM** [comment]
Hi @pmackay,

Indeed, you'll need a delayed job worker running for emails to go out.

On other servers I have the monit file stored in `/etc/monit/conf.d/openfoodnetwork`.

For path configuration, I reckon it might work well to pass in a `RAILS_ROOT` environment variable. Then all paths could be made relative to that path. The monit config would have to be modified to pass that environment var, as would the buildkite config for the CI scripts (the latter should be straight-forward to do).

**Comment by pmackay** [comment]
Think @RohanM has now completed this.
