### ISSUE TITLE
Seeding Spree fails on Vagrant Box

### ISSUE THREAD

**Issue by MikeiLL** [openfoodfoundation/ofn_deployment#37]
This is probably a configuration error and not a bug, so I hope it's okay to post here.

Getting error on Vagrant Up:

```
failed: [default] => {"changed": true, "cmd": ["bash", "-lc", "/home/vagrant/apps/pcolacoop/shared/config/seed.sh RAILS_ENV=test"], "delta": "0:00:33.402738", "end": "2015-09-01 04:56:20.873064", "rc": 1, "start": "2015-09-01 04:55:47.470326", "warnings": []}
stderr: stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
stty: standard input: Inappropriate ioctl for device
rake aborted!
NoMethodError: undefined method `name' for nil:NilClass
/home/vagrant/apps/pcolacoop/current/db/seeds.rb:24:in `<top (required)>'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `block in load'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
/home/vagrant/.gem/ruby/1.9.1/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:245:in `load'
/home/vagrant/.gem/ruby/1.9.1/gems/railties-3.2.21/lib/rails/engine.rb:525:in `load_seed'
/home/vagrant/.gem/ruby/1.9.1/gems/activerecord-3.2.21/lib/active_record/railties/databases.rake:347:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
stdout: [db:seed] Seeding Spree
loading ruby /home/vagrant/.gem/ruby/1.9.1/bundler/gems/spree-afcc23e489eb/core/db/default/spree/countries.rb
loading ruby /home/vagrant/.gem/ruby/1.9.1/bundler/gems/spree-afcc23e489eb/core/db/default/spree/roles.rb
loading ruby /home/vagrant/.gem/ruby/1.9.1/bundler/gems/spree-afcc23e489eb/core/db/default/spree/states.rb
loading ruby /home/vagrant/.gem/ruby/1.9.1/bundler/gems/spree-afcc23e489eb/core/db/default/spree/zones.rb
loading ruby /home/vagrant/.gem/ruby/1.9.1/bundler/gems/spree_auth_devise-ba95589a8536/db/default/users.rb
Create the admin user (press enter for defaults).
Email [spree@example.com]: Password [spree123]: 
Done!
Country is 
[db:seed] loading states yaml
States: [{"name"=>"Tasmania", "country_id"=>"12", "id"=>"101", "abbr"=>"Tas"}, {"name"=>"Victoria", "country_id"=>"12", "id"=>"102", "abbr"=>"Vic"}, {"name"=>"New South Wales", "country_id"=>"12", "id"=>"103", "abbr"=>"NSW"}, {"name"=>"ACT", "country_id"=>"12", "id"=>"104", "abbr"=>"ACT"}, {"name"=>"Queensland", "country_id"=>"12", "id"=>"105", "abbr"=>"QLD"}, {"name"=>"South Australia", "country_id"=>"12", "id"=>"106", "abbr"=>"SA"}, {"name"=>"Northern Territory", "country_id"=>"12", "id"=>"107", "abbr"=>"NT"}, {"name"=>"Western Australia", "country_id"=>"12", "id"=>"108", "abbr"=>"WA"}]
[db:seed] loading suburbs csv

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/username/install.retry

default                    : ok=72   changed=55   unreachable=0    failed=1 
```
I haven't used Spree before. Seeing that the `spree@example.com` is referenced in the file `spree/api/testing_support/helpers_decorator.rb` and it doesn't look like it's something that needs to be configured. Had originally gotten this error using the US i10n repository, so was trying the AU one to see if the error was in the i10n repo.

Also is the output `to retry, use: --limit @/Users/username/install.retry` referring to: `$ vagrant --limit provision`? When I run that (or `vagrant provision` again), the output also includes 

`stderr: rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Name has already been taken`

**Comment by pmackay** [comment]
Does your vars.xml config match the i10n repo, in terms of country code, etc?

**Comment by MikeiLL** [comment]
Do you mean vars._yml_? For troubleshooting, I set the `vars.yml` back to matching the example:

```
country_code: AU
locale: en
language: en_AU.UTF-8
timezone: Melbourne
i10n_repo: https://github.com/openfoodfoundation/i10n_au.git
```

**Comment by MikeiLL** [comment]
Doesn't seem to be any .xml file in either the ofn_deployment or openfoodnework repositories.

Making some progress. These settings worked:

```
country_code: AU
locale: en-AU
language: en_AU.UTF-8
timezone: Melbourne
i10n_repo: https://github.com/openfoodfoundation/i10n_au.git
```

The other configs I had tried were these:

```
country_code: US
locale: en-US
language: en_US.UTF-8
timezone: America/Chicago
i10n_repo: https://github.com/openfoodfoundation/i10n_us
```

Error:

```
[db:seed] loading suburbs csv
[db:seed] Seeding states for United States
State: ["states_043", {"name"=>"Michigan", "country_id"=>49, "abbr"=>"MI"}]

FATAL: all hosts have already failed -- aborting
```
The repository for en-US has surburbs data stored in .yml files in a subdirectory of the repo, and it looks like seeds.rb is set to parse the data from a csv file:

```
suburbs_file = File.join ['db', 'suburbs.csv']

# -- Seeding States
puts "[db:seed] Seeding states for " + country.name

states.each do |state|
  puts "State: " + state.to_s
  unless Spree::State.find_by_name(state['name'])
    Spree::State.create!({"name"=>state['name'], "abbr"=>state['abbr'], :country=>country}, without_protection: true)
  end
  puts "set id"
  states_ids[state['abbr']] = Spree::State.where(abbr: state['abbr']).where(country_id: country.id).first.id
end
#...
CSV.foreach(suburbs_file, {headers: true, header_converters: :symbol}) do |row|
  postcode = row[:postcode]
  name = row[:name]
  lat = row[:latitude]
  long = row[:longitude]
  state_id = states_ids[row[:state_id]]
  statement += "(#{postcode},$$#{name}$$,#{state_id},#{lat},#{long}),"
end
statement[-1] = ';'
```

So am I figuring correctly that we either need to refactor the ruby code to behave differently if it doesn't detect a `suburbs.csv` file _or_ we need to change the i10n_us repository to contain the suburbs data in csv format?

**Comment by pmackay** [comment]
I would change the format of the i10n_us suburbs file so it is a CSV file. In fact I just did this for the GB repo on Monday. The seeds stuff is a bit messy but I’ve been trying to integrate some simplifications that Raf worked on recently for the Norway deployment.

-- 
Paul Mackay

On 2 September 2015 at 04:00:43, Mike iLL Kilmer (notifications@github.com) wrote:

Doesn't seem to be any .xml file in either the ofn_deployment or openfoodnework repositories.

Making some progress. These settings worked:

country_code: AU
locale: en-AU
language: en_AU.UTF-8
timezone: Melbourne
i10n_repo: https://github.com/openfoodfoundation/i10n_au.git

The other configs I had tried were these:

country_code: US
locale: en-US
language: en_US.UTF-8
timezone: America/Chicago
i10n_repo: https://github.com/openfoodfoundation/i10n_us

Error:

[db:seed] loading suburbs csv
[db:seed] Seeding states for United States
State: ["states_043", {"name"=>"Michigan", "country_id"=>49, "abbr"=>"MI"}]

FATAL: all hosts have already failed -- aborting

The repository for en-US has surburbs data stored in .yml files in a subdirectory of the repo, and it looks like seeds.rb is set to parse the data from a csv file:

suburbs_file = File.join ['db', 'suburbs.csv']

# -- Seeding States
puts "[db:seed] Seeding states for " + country.name

states.each do |state|
  puts "State: " + state.to_s
  unless Spree::State.find_by_name(state['name'])
    Spree::State.create!({"name"=>state['name'], "abbr"=>state['abbr'], :country=>country}, without_protection: true)
  end
  puts "set id"
  states_ids[state['abbr']] = Spree::State.where(abbr: state['abbr']).where(country_id: country.id).first.id
end
#...
CSV.foreach(suburbs_file, {headers: true, header_converters: :symbol}) do |row|
  postcode = row[:postcode]
  name = row[:name]
  lat = row[:latitude]
  long = row[:longitude]
  state_id = states_ids[row[:state_id]]
  statement += "(#{postcode},$$#{name}$$,#{state_id},#{lat},#{long}),"
end
statement[-1] = ';'

So am I figuring correctly that we either need to refactor the ruby code to behave differently if it doesn't detect a suburbs.csv file or we need to change the i10n_us repository to contain the suburbs data in csv format?

**Comment by MikeiLL** [comment]
Yes. I have suburbs in a csv file now. Problem was with states file, I think.

I've found a states.yml file that looks fairly similar to the AU one that allows a full deployment (at least according to stdout). Each State looks like:
```
states_020: 
  name: Alaska
  country_id: "214"
  id: "403740659"
  abbr: AK
```
This creates an error because the array ends up looking like:
```
[ states_020,
  { name => Alaska
  country_id => "214"
  id => "403740659"
  abbr => AK }, etc]
```
Removing the outer level state number puts the info at the depth the seeds.rb file is looking for, and I imagine it will also provide a workable dictionary if I move the state number into it's own key. 

```
  name: Pennsylvania
  country_id: "214"
  id: "471711976"
  abbr: PA
```
Added some debug output to seeds.rb:
```
states.each do |state|
  puts "State: " + state.to_s
  puts "Got this far." 
  puts state['name']  # but not as far as this
  unless Spree::State.find_by_name(state['name'])
    puts "did not find by name."
    Spree::State.create!({"name"=>state['name'], "abbr"=>state['abbr'], :country=>country}, without_protection: true)
    puts "i said " + "name"=>state['name']
  end
  puts "set id"
  states_ids[state['abbr']] = Spree::State.where(abbr: state['abbr']).where(country_id: country.id).first.id
end
```
Still getting:
```
Country is United States
[db:seed] loading states yaml
States: {"name"=>"Newfoundland and Labrador", "country_id"=>"35", "id"=>"61", "abbr"=>"NL"}
[db:seed] loading suburbs csv
[db:seed] Seeding states for United States
State: ["name", "Newfoundland and Labrador"]
Got this far.

FATAL: all hosts have already failed -- aborting
```

Running the original AU data that worked, with the new data to see what output is supposed to look like. Ah. Output for working states.yml file is escaped! Turns out my .yml markup was invalid. Redeploying now...

Right now wondering if it would make any sense to check validity of yaml markup as part of deployment. maybe with http://www.kuwata-lab.com/kwalify/ruby/users-guide.03.html. But I am very new to Ruby.

At any rate, once I get this working I will push changes to the i10n_us repo. 

I do have another question, though. Where is the URL I will visit once deployed dev site is running? I guess it will be in my `/etc/hosts` file, won't it?

**Comment by pmackay** [comment]
I think the states needs to be formatted as a top level array containing hashes, e.g.:

```
---
- name: Aberdeen City
  country_id: '213'
  id: '101'
  abbr: AbC
- name: Aberdeenshire
  country_id: '213'
  id: '102'
  abbr: AbS
```

This again is a change compared with earlier versions and something I changed for GB.

What machine are you deploying to?

**Comment by MikeiLL** [comment]
Whatever Vagrant box is defined in the ofn_deployment repository. Ubuntu 64 in Virtual box.
It's getting a little bit further now and yes - states all hashes at top level of array.
Having trouble when gets to:
```
CSV.foreach(suburbs_file, {headers: true, header_converters: :symbol}) do |row|
```
Ah. Because csv file had USA style headers (city, state, zip_code, etc) as opposed to name, post_code, state_id.

Thanks for your help on this. This should probably be obvious, but can you tell me the simplest place to find the URL I can access the dev deployment at (once it's up)?

**Comment by pmackay** [comment]
If using vagrant then it should be `localhost:8080`. This is controlled by
this line in the Vagrantfile:

`config.vm.network "forwarded_port", guest: 80, host: 8080`

The commented out 443 line is for `https` I think....

**Comment by MikeiLL** [comment]
Clawing my way down the seeds.rb file. Getting as far as

```
unless Suburb.find_by_name(name)
  puts "[db:seed] Seeding suburbs for country.name"
```
Seem to be snagged at:
```
  connection = ActiveRecord::Base.connection()
  puts "ANd the SQL is: " + statement
  connection.execute(statement)
```
What's going on with those `$` around `name`?
`(#{postcode},$$#{name}$$,#{state_id},#{lat},#{long})`

**Comment by MikeiLL** [comment]
Okay this is about the simplest query:
```
[db:seed] Seeding suburbs for country.name
ANd the SQL is: INSERT INTO suburbs (postcode,name,state_id,latitude,longitude) VALUES
(00501,Holtsville,48,40.922326,-72.637078);
```
```
State ids:{"MI"=>1, "SD"=>2, "WA"=>3, "WI"=>4, "AZ"=>5, "IL"=>6, "NH"=>7, "NC"=>8, "KS"=>9, "MO"=>10, "AR"=>11, "NV"=>12, "DC"=>13, "ID"=>14, "NE"=>15, "PA"=>16, "HI"=>17, "UT"=>18, "VT"=>19, "DE"=>20, "RI"=>21, "OK"=>22, "LA"=>23, "MT"=>24, "TN"=>25, "MD"=>26, "FL"=>27, "VA"=>28, "MN"=>29, "NJ"=>30, "OH"=>31, "CA"=>32, "ND"=>33, "ME"=>34, "IN"=>35, "TX"=>36, "OR"=>37, "WY"=>38, "AL"=>39, "IA"=>40, "MS"=>41, "KY"=>42, "NM"=>43, "GA"=>44, "CO"=>45, "MA"=>46, "CT"=>47, "NY"=>48, "SC"=>49, "AK"=>50, "WV"=>51, "ON"=>55, "QC"=>56, "NS"=>57, "NB"=>58, "MB"=>59, "BC"=>60, "PE"=>61, "SK"=>62, "AB"=>63, "NL"=>64}
```
Not getting past: `connection.execute(statement)`

**Comment by MikeiLL** [comment]
Poking around the DB via `sudo -u postgres -i`, `psql`, `\list`, `\connect openfoodnetwork`. `spree_states` are populated with US data.

`suburbs` table is as described:
```
openfoodnetwork=# select * from suburbs;
 id | name | postcode | latitude | longitude | state_id 
----+------+----------+----------+-----------+----------
(0 rows)

```
This is a string of the connection object:
`#<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x000000093ba890>`

Not getting past `connection.execute(statement)`. 

Weird.

**Comment by MikeiLL** [comment]
The problem seems to have been _either_ that the line endings of the csv file were not windows, that some of the "outlaying territories" did not have entries in the states.yml file, or _both_.
