### ISSUE TITLE
[webserver | restart unicorn step 2] Interactive authentication required

### ISSUE THREAD

**Issue by MikeiLL** [openfoodfoundation/ofn_deployment#43]
Can't seem to get past this step on EC2 instance.

```
NOTIFIED: [webserver | restart unicorn step 2] ******************************** 
failed: [staging.usfoodcoop.org] => {"failed": true}
msg: Failed to stop unicorn_ofn_america.service: Interactive authentication required.
Failed to start unicorn_ofn_america.service: Interactive authentication required.
```

Tried replacing with `raw: sudo systemctl restart unicorn_ofn_america.service`, which succeeds, but - aside from the fact that user would have to replace the app name manually - seems to make unicorn inaccessible to the rails app which is of course not owned by root, causing `.sock failed (111: Connection refused` error.

**Comment by mkllnk** [comment]
I'm wondering if 7ebe742 fixes your problem.

**Comment by MikeiLL** [comment]
I'm fairly sure it will. Next time I deploy, will check. Up and running at the moment. I think I may have just started the service manually. Have the canada-updates branch checked out locally. Thank you.

**Comment by pmackay** [comment]
@MikeiLL are you ok to close this? Or can you test it?

**Comment by MikeiLL** [comment]
@pmackay we're not even running it on an EC2 instance at this point, and it may be a few weeks before I have a chance to play around with it again (on another server). If you feel it should be tested, please let mw know and I'll find some time, otherwise go ahead and close. Thank you.

**Comment by pmackay** [comment]
Closing but please reopen @MikeiLL if you think this could still be an issue.
