### ISSUE TITLE
AWS not set up

### ISSUE THREAD

**Issue by mkllnk** [openfoodfoundation/ofn_deployment#45]
After I deployed the Canadian server, AWS wasn't set up (Image Settings as Spree admin). I have not tried to reproduce this. But it would be good to verify that this is working.

**Comment by pmackay** [comment]
I notice you put back the s3 config in dbf10ac722e44eeefbec6eaf9f13d4410b6f0551. I removed it earlier cos of #29. Should it be that the deploy script sets it up to auto populate the admin UI?

**Comment by pmackay** [comment]
Also note openfoodfoundation/openfoodnetwork/issues/517.

**Comment by mkllnk** [comment]
Ah, okay. I assumed that the database would be populated with these variables. Otherwise is doesn't make much sense to put them into the vars file, or does it?

What do you think the ideal scenario should look like?

**Comment by pmackay** [comment]
Is there a way to prepopulate the database from variables in the ansible config? Would @RohanM have an idea? If so, would be good to get that working. But if not, should we remove the s3 config again?

**Comment by mkllnk** [comment]
Well, there are two things. There is the S3 config for storing images (products, enterprises, groups). And there is the DB2fog config file for backups. The DB2fog config file uses the S3 config from the database.

So if that feature is broken anyway, we can remove the code. We have to change the wiki pages as well to describe how to configure S3 for images and backups manually.

But it would be interesting to hear @RohanM's opinion first.

**Comment by pmackay** [comment]
It looks like the db2fog config still uses one var from ansible:

```
DB2Fog.config = {
  :aws_access_key_id     => Spree::Config[:s3_access_key],
  :aws_secret_access_key => Spree::Config[:s3_secret],
  :directory             => "{{ s3_bucket }}-backups",
  :provider              => 'AWS'
}
```
Is there a way of inserting the spree config during provisioning process?

**Comment by mkllnk** [comment]
True. That should probably be replaced.

I'm sure there is a way, but I don't know how complicated it would be. I have not written Ansible playbooks yet.

**Comment by pmackay** [comment]
I dont think its the ansible bit that’s hard. Its if there is a logical way via a config file or database update that the values could be set. What’s the best mechanism to do that? If that’s known, can probably get ansible to do it.

**Comment by pmackay** [comment]
For now perhaps its simplest just to maintain the `s3_bucket` variable and also have the UI config for images.

**Comment by pmackay** [comment]
Closing as I think agreement is we're not expecting Ansible to do a full AWS config.
